# Generated by Django 3.2 on 2021-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='profile_pics')),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
