# Generated by Django 3.2 on 2021-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
